interfaces:
-   enabled: true
    name: GigabitEthernet0/0
-   enabled: true
    name: GigabitEthernet0/1
-   enabled: true
    name: GigabitEthernet0/2
-   enabled: true
    name: GigabitEthernet0/3
-   enabled: true
    name: GigabitEthernet1/0
-   enabled: true
    name: GigabitEthernet1/1
-   enabled: true
    name: GigabitEthernet1/2
-   enabled: true
    name: GigabitEthernet1/3
-   enabled: true
    name: Vlan1
