l3_interfaces:
-   name: GigabitEthernet0/0
-   name: GigabitEthernet0/1
-   name: GigabitEthernet0/2
-   name: GigabitEthernet0/3
-   name: GigabitEthernet1/0
-   name: GigabitEthernet1/1
-   name: GigabitEthernet1/2
-   name: GigabitEthernet1/3
-   ipv4:
    -   address: 172.16.5.22/24
    name: Vlan1
