lacp_interfaces:
-   name: GigabitEthernet0/0
-   name: GigabitEthernet0/1
-   name: GigabitEthernet0/2
-   name: GigabitEthernet0/3
-   name: GigabitEthernet1/0
-   name: GigabitEthernet1/1
-   name: GigabitEthernet1/2
-   name: GigabitEthernet1/3
-   name: Vlan1
